language: ruby
cache: bundler
dist: xenial

bundler_args: --jobs 7 --without docs debug

matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: 2.6.0
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

script: bundle exec rake spec

branches:
  only:
  - master
